# Generated by Django 5.0.4 on 2024-04-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(default='No description', max_length=150),
        ),
    ]
