# Generated by Django 5.0.4 on 2024-04-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0006_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
