# Generated by Django 5.0.4 on 2024-04-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0008_alter_category_name_alter_food_name_alter_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img_url',
            field=models.CharField(default='www', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
