# Generated by Django 5.0.4 on 2024-04-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0009_food_img_url_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
